stages:
  - build
  - unit
  - integration
  - e2e

variables:
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_DB: testdb

before_script:
  # Установка зависимостей (если требуется)
  - apt-get update && apt-get install -y curl

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

unit_tests:
  stage: unit
  script:
    - docker-compose -f docker-compose.yml up -d xellarium-test-db
    - docker-compose -f docker-compose.yml run --rm unit-tests
  allow_failure: false

integration_tests:
  stage: integration
  script:
    - docker-compose -f docker-compose.yml up -d xellarium-test-db
    - docker-compose -f docker-compose.yml run --rm integration-tests
  allow_failure: false

e2e_tests:
  stage: e2e
  script:
    - docker-compose -f docker-compose.yml up -d test-api
    - docker-compose -f docker-compose.yml run --rm e2e-tests
  allow_failure: false

after_script:
  # Откат изменений базы данных (если тесты не прошли)
  - docker-compose -f docker-compose.yml down -v
