services:
  nginx:
    container_name: xellarium-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - api2
      - api3
      - pgadmin
      - nginx-mirror
  nginx-mirror:
    container_name: xellarium-nginx-mirror
    image: nginx:latest
    volumes:
      - ./nginx/nginx_mirror.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "81:80"
    depends_on:
      - api-mirror
      - api2-mirror
      - api3-mirror
      - pgadmin-mirror
  pgadmin:
    container_name: xellarium-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./pgadmin/pgpass:/pgpass
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - xellarium-db
  pgadmin-mirror:
    container_name: xellarium-pgadmin-mirror
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./pgadmin/pgpass-mirror:/pgpass
      - ./pgadmin/servers-mirror.json:/pgadmin4/servers.json
    ports:
      - "5051:80"
    depends_on:
      - xellarium-replica
  xellarium-db:
    container_name: xellarium-db
    image: xellarium.postgres
    build:
      context: .
      dockerfile: Dockerfile_Postgres
    environment:
      - POSTGRES_USER=uncledrema
      - POSTGRES_PASSWORD=dremakorol
      - PGDATA=/var/lib/postgresql/data/
      - TARGET=xellarium-replica
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5433:5432"
      
  xellarium-replica:
    container_name: xellarium-replica
    image: xellarium.postgres
    build:
      context: .
      dockerfile: Dockerfile_Postgres
    environment:
      - POSTGRES_USER=uncledrema
      - POSTGRES_PASSWORD=dremakorol
      - PGDATA=/var/lib/postgresql/data/
      - TARGET=xellarium-db
    volumes:
      - replica_pgdata:/var/lib/postgresql/data
      - ./pg_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5434:5432"
    depends_on:
      - xellarium-db
        
  api:
    container_name: api
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-db;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-db
    ports:
      - "5000:8080"
  
  api2:
    container_name: api2
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-db;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-db
    ports:
      - "5001:8080"
  
  api3:
    container_name: api3
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-db;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-db
    ports:
      - "5002:8080"
    
  api-mirror:
    container_name: api-mirror
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-replica;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-replica
    ports:
      - "5100:8080"
  
  api2-mirror:
    container_name: api2-mirror
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-replica;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-replica
    ports:
      - "5101:8080"
  
  api3-mirror:
    container_name: api3-mirror
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-replica;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-replica
    ports:
      - "5102:8080"
  
  client:
    container_name: client
    image: xellarium.client
    build:
      context: ./src/
      dockerfile: Dockerfile_WebClient
    depends_on:
      - api
    volumes:
      - ./src/Xellarium.Client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5080:80"
  
  xellarium-test-db:
    container_name: xellarium-test-db
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data

  test-api:
    container_name: test-api
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Testing
      Databases__Postgres__ConnectionString: "Host=xellarium-test-db;Port=5434;Database=testdb;Username=testuser;Password=testpassword"
    depends_on:
      - xellarium-test-db
    ports:
      - "5001:8080"

  unit-tests:
    image: xellarium-tests
    build:
      context: .
      dockerfile: Dockerfile
    command: --filter "(TestCategory = Unit)" --property:WarningLevel=0
    environment:
      ConnectionStrings__Postgres: "Host=xellarium-test-db;Database=testdb;Username=testuser;Password=testpassword"
    depends_on:
      - xellarium-test-db
    volumes:
      - ./allure-results:/app/test/allure-results

  integration-tests:
     image: xellarium-tests
     build:
       context: .
       dockerfile: Dockerfile
     command: --filter "(TestCategory = Integration)" --property:WarningLevel=0
     environment:
       ConnectionStrings__Postgres: "Host=xellarium-test-db;Database=testdb;Username=testuser;Password=testpassword"
     depends_on:
       - xellarium-test-db
     volumes:
       - ./allure-results:/app/test/allure-results

  e2e-tests:
     image: xellarium-tests
     build:
       context: .
       dockerfile: Dockerfile
     command: --filter "(TestCategory = EndToEnd)" --property:WarningLevel=0
     environment:
       ServerAddress: "http://test-api:8080/"
     depends_on:
       - test-api
     volumes:
       - ./allure-results:/app/test/allure-results

volumes:
  pgdata-test:
  pgdata:
  replica_pgdata:
    