services:
  nginx:
    container_name: xellarium-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - pgadmin
  pgadmin:
    container_name: xellarium-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./pgadmin/pgpass:/pgpass
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - xellarium-db
  xellarium-db:
    container_name: xellarium-db
    image: postgres:15
    environment:
      - POSTGRES_USER=uncledrema
      - POSTGRES_PASSWORD=dremakorol
      - PGDATA=/var/lib/postgresql/data/
      - TARGET=xellarium-replica
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  api:
    container_name: api
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      Databases__Postgres__ConnectionString: "Host=xellarium-db;Port=5432;Database=xellarium;Username=uncledrema;Password=dremakorol"
    depends_on:
      - xellarium-db
    ports:
      - "5000:8080"
  
  client:
    container_name: client
    image: xellarium.client
    build:
      context: ./src/
      dockerfile: Dockerfile_WebClient
    depends_on:
      - api
    volumes:
      - ./src/Xellarium.Client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5080:80"
  
  xellarium-test-db:
    container_name: xellarium-test-db
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data

  test-api:
    container_name: test-api
    image: xellarium.server
    build:
      context: ./src/
      dockerfile: Dockerfile_WebApi
    environment:
      ASPNETCORE_ENVIRONMENT: Testing
      Databases__Postgres__ConnectionString: "Host=xellarium-test-db;Database=testdb;Username=testuser;Password=testpassword"
    depends_on:
      - xellarium-test-db
    ports:
      - "5001:8080"

  unit-tests:
    image: xellarium-tests
    build:
      context: .
      dockerfile: Dockerfile
    command: --filter "(TestCategory = Unit)" --property:WarningLevel=0
    environment:
      ConnectionStrings__Postgres: "Host=xellarium-test-db;Database=testdb;Username=testuser;Password=testpassword"
    depends_on:
      - xellarium-test-db
    volumes:
      - ./allure-results:/app/test/allure-results

  integration-tests:
     image: xellarium-tests
     build:
       context: .
       dockerfile: Dockerfile
     command: --filter "(TestCategory = Integration)" --property:WarningLevel=0
     environment:
       ConnectionStrings__Postgres: "Host=xellarium-test-db;Database=testdb;Username=testuser;Password=testpassword"
       ApiUri: "http://test-api:8080/api/v2/"
     depends_on:
       - xellarium-test-db
       - test-api
     volumes:
       - ./allure-results:/app/test/allure-results

  e2e-tests:
     image: xellarium-tests
     build:
       context: .
       dockerfile: Dockerfile
     command: --filter "(TestCategory = EndToEnd)" --property:WarningLevel=0
     environment:
       ServerAddress: "http://test-api:8080/"
     depends_on:
       - test-api
     volumes:
       - ./allure-results:/app/test/allure-results

volumes:
  pgdata-test:
  pgdata:
    