# Этап сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

# Копируем проект и восстанавливаем зависимости
COPY . .
RUN dotnet publish ./Xellarium.Client/ -c Release -o /app/client

# Этап с Nginx для обслуживания клиентского приложения
FROM nginx:alpine AS runtime

# Удаляем стандартные конфигурации Nginx
RUN rm -rf /usr/share/nginx/html/*

# Копируем опубликованные файлы из этапа сборки в Nginx
COPY --from=build /app/client/wwwroot /usr/share/nginx/html

# Открываем порт для Nginx
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]