name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y
        
      - name: Install Allure
        run: |
          sudo apt-get install -y default-jre  # Устанавливаем Java, необходимую для Allure
          sudo mkdir -p /opt/allure  # Создаём директорию для Allure
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.tgz -o allure.tgz
          sudo tar -xzvf allure.tgz -C /opt/allure
          sudo ln -s /opt/allure/allure-2.20.0/bin/allure /usr/bin/allure

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Run unit tests
        if: success() || failure()
        run: |
         docker-compose run --rm unit-tests
         if grep -q '"status": "failed"' ./allure-results/*.json; then
           echo "TESTS_STATUS=failed" >> $GITHUB_ENV
         else
           echo "TESTS_STATUS=success" >> $GITHUB_ENV
         fi

      - name: Run integration tests
        if: success() || failure()
        run: |
          echo ${{ env.TESTS_STATUS }}
          docker-compose run --rm -e TESTS_STATUS=${{ env.TESTS_STATUS }} integration-tests
          if grep -q '"status": "failed"' ./allure-results/*.json; then
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          fi
        env:
          TESTS_STATUS: ${{ env.TESTS_STATUS }}

      - name: Run E2E tests
        if: success() || failure()
        run: |
          echo ${{ env.TESTS_STATUS }}
          docker-compose run --rm -e TESTS_STATUS=${{ env.TESTS_STATUS }} e2e-tests
        env:
          TESTS_STATUS: ${{ env.TESTS_STATUS }}

      - name: Print all folders
        if: success() || failure()
        run: ls -la .
        
      - name: Print all folders in test
        if: success() || failure()
        run: ls -la ./test
        
      - name: Set permissions for allure-results
        if: success() || failure()
        run: sudo chmod -R 755 allure-results

      - name: Generate Allure report
        if: success() || failure()
        run: |
          allure generate ./allure-results -o ./allure-report

      - name: Upload Allure report as artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload Allure results as artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      - name: Clean up
        if: success() || failure()
        run: docker-compose down -v
